---
services:
  localstack:
    image: 'gresau/localstack-persist:4.3.0'
    ports:
      - '4566:4566'  # LocalStack Gateway
      - '4510-4559:4510-4559'  # external services port range
    volumes:
      - '.localstack_data:/persisted-data'
      - '/var/run/docker.sock:/var/run/docker.sock:ro'
