---
services:
  localstack:
    image: 'gresau/localstack-persist:4.3.0'
    ports:
      - '4566:4566'  # LocalStack Gateway
      - '4510-4559:4510-4559'  # external services port range
    volumes:
      - '.localstack_data:/persisted-data'
      - '/var/run/docker.sock:/var/run/docker.sock:ro'
    healthcheck:
      test: ['CMD', 'curl', '-f', 'http://localhost:4566/_localstack/health']
      interval: '5s'
      timeout: '5s'
      retries: '3'
      start_period: '10s'

  redis:
    image: 'redis:7-alpine'
    ports:
      - '6379:6379'
    healthcheck:
      test: ['CMD', 'redis-cli', 'ping']
      interval: '5s'
      timeout: '5s'
      retries: '3'
      start_period: '10s'
